version: '2'
services:
  sapp-app:
    image: sapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sapp-mssql:1433;database=sapp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8050:8050
  sapp-mssql:
    extends:
      file: mssql.yml
      service: sapp-mssql
